# Kustomization patch to add Datadog log collection annotations
# to all sock-shop deployments
#
# Usage: Apply this with Kustomize to add annotations without modifying base files
# This approach is only needed if using datadog-values-selective.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sock-shop

resources:
  - ../manifests/base

patches:
  # Front-end
  - target:
      kind: Deployment
      name: front-end
    patch: |-
      - op: add
        path: /spec/template/metadata/annotations
        value:
          ad.datadoghq.com/front-end.logs: '[{"source":"nodejs","service":"front-end"}]'
  
  # Catalogue
  - target:
      kind: Deployment
      name: catalogue
    patch: |-
      - op: add
        path: /spec/template/metadata/annotations
        value:
          ad.datadoghq.com/catalogue.logs: '[{"source":"golang","service":"catalogue"}]'
  
  # User
  - target:
      kind: Deployment
      name: user
    patch: |-
      - op: add
        path: /spec/template/metadata/annotations
        value:
          ad.datadoghq.com/user.logs: '[{"source":"golang","service":"user"}]'
  
  # Carts
  - target:
      kind: Deployment
      name: carts
    patch: |-
      - op: add
        path: /spec/template/metadata/annotations
        value:
          ad.datadoghq.com/carts.logs: '[{"source":"java","service":"carts"}]'
  
  # Orders
  - target:
      kind: Deployment
      name: orders
    patch: |-
      - op: add
        path: /spec/template/metadata/annotations
        value:
          ad.datadoghq.com/orders.logs: '[{"source":"java","service":"orders"}]'
  
  # Payment
  - target:
      kind: Deployment
      name: payment
    patch: |-
      - op: add
        path: /spec/template/metadata/annotations
        value:
          ad.datadoghq.com/payment.logs: '[{"source":"golang","service":"payment"}]'
  
  # Shipping
  - target:
      kind: Deployment
      name: shipping
    patch: |-
      - op: add
        path: /spec/template/metadata/annotations
        value:
          ad.datadoghq.com/shipping.logs: '[{"source":"java","service":"shipping"}]'
  
  # Queue Master
  - target:
      kind: Deployment
      name: queue-master
    patch: |-
      - op: add
        path: /spec/template/metadata/annotations
        value:
          ad.datadoghq.com/queue-master.logs: '[{"source":"java","service":"queue-master"}]'
