datadog:
  site: us5.datadoghq.com
  apiKeyExistingSecret: datadog-secret
  clusterName: sockshop-kind

  logs:
    enabled: true
    containerCollectAll: false
    containerCollectUsingFiles: true
    containerInclude:
      - "kube_namespace:sock-shop"

  # keep all these false
  apm:
    enabled: false
  processAgent:
    enabled: false
  admissionController:
    enabled: false
  orchestratorExplorer:
    enabled: false
  kubeStateMetricsCore:
    enabled: false
  clusterChecks:
    enabled: false

  # kind-safe runtime
  useHostPID: false
  containerImageCollection:
    enabled: false
  containerLifecycle:
    enabled: false
  kubelet:
    useApiServer: true

clusterAgent:
  enabled: false

systemProbe:
  enabled: false

agents:
  tolerations:
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Exists"
      effect: "NoSchedule"
    - key: "node-role.kubernetes.io/master"
      operator: "Exists"
      effect: "NoSchedule"

  containers:
    # ensure no sidecars
    traceAgent:
      enabled: false

    # >>> critical: fix hostname crash + force APM off at the container
    agent:
      env:
        - name: DD_HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: DD_APM_ENABLED
          value: "false"
