apiVersion: datadoghq.com/v2alpha1
kind: DatadogAgent
metadata:
  name: datadog
  namespace: datadog
spec:
  global:
    site: "us5.datadoghq.com"          # keep your site
    clusterName: "sockshop-kind"
    credentials:
      apiSecret:
        secretName: "datadog-secret"
        keyName: "api-key"
    tags:
      - "env:dev"
  features:
    logCollection:
      enabled: true
      containerCollectAll: false
      containerCollectUsingFiles: true
      containerIncludeLogs:
        - "kube_namespace:sock-shop"   # start narrow; widen later if needed
  override:
    nodeAgent:
      daemonset:
        spec:
          template:
            spec:
              tolerations:
                - key: "node-role.kubernetes.io/control-plane"
                  operator: "Exists"
                  effect: "NoSchedule"
                - key: "node-role.kubernetes.io/master"
                  operator: "Exists"
                  effect: "NoSchedule"
