# Selective Datadog Configuration for Sock-Shop Demo
# This configuration requires pod annotations but provides fine-grained control
# Use this if you want to explicitly control which pods send logs

datadog:
  site: us5.datadoghq.com
  apiKeyExistingSecret: datadog-secret
  clusterName: sockshop-kind

  logs:
    enabled: true
    containerCollectUsingFiles: true
    containerCollectAll: false  # Only collect from annotated pods

  kubelet:
    tlsVerify: false
    useApiServer: true

  apm:
    enabled: false
  processAgent:
    enabled: false
  admissionController:
    enabled: false
  orchestratorExplorer:
    enabled: false
  kubeStateMetricsCore:
    enabled: false
  clusterChecks:
    enabled: false
  
  useHostPID: false
  containerImageCollection:
    enabled: false
  containerLifecycle:
    enabled: false

clusterAgent:
  enabled: false

systemProbe:
  enabled: false

agents:
  tolerations:
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Exists"
      effect: "NoSchedule"
    - key: "node-role.kubernetes.io/master"
      operator: "Exists"
      effect: "NoSchedule"
  
  useHostNetwork: true

  containers:
    traceAgent:
      enabled: false
    
    agent:
      env:
        - name: DD_HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: DD_APM_ENABLED
          value: "false"
        - name: DD_LOGS_ENABLED
          value: "true"
        - name: DD_LOGS_CONFIG_K8S_CONTAINER_USE_FILE
          value: "true"
        - name: DD_LOG_LEVEL
          value: "info"
