apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "8"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"name":"orders"},"name":"orders","namespace":"sock-shop"},"spec":{"replicas":1,"selector":{"matchLabels":{"name":"orders"}},"template":{"metadata":{"labels":{"name":"orders"}},"spec":{"containers":[{"args":["-cp","/app.jar","-Xms64m","-Xmx128m","-XX:+UseG1GC","-Djava.security.egd=file:/dev/urandom","-Dspring.zipkin.enabled=false","-Dloader.path=/opt/lib","org.springframework.boot.loader.PropertiesLauncher","--port=8080"],"command":["/usr/bin/java"],"image":"quay.io/powercloud/sock-shop-orders:latest","imagePullPolicy":"IfNotPresent","name":"orders","ports":[{"containerPort":8080}],"resources":{"limits":{"cpu":"500m","memory":"500Mi"},"requests":{"cpu":"100m","memory":"300Mi"}},"securityContext":{"capabilities":{"drop":["all"]},"readOnlyRootFilesystem":true,"runAsNonRoot":true},"volumeMounts":[{"mountPath":"/tmp","name":"tmp-volume"}]}],"nodeSelector":{"node-role.kubernetes.io/worker":""},"volumes":[{"emptyDir":{"medium":"Memory"},"name":"tmp-volume"}]}}}}
  creationTimestamp: "2025-10-14T11:10:59Z"
  generation: 8
  labels:
    name: orders
  name: orders
  namespace: sock-shop
  resourceVersion: "370793"
  uid: 003b7489-78b5-4218-9baf-da8c26a38ae3
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: orders
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2025-10-28T13:03:54+05:30"
      creationTimestamp: null
      labels:
        name: orders
    spec:
      containers:
      - args:
        - -cp
        - /app.jar
        - -Xms64m
        - -Xmx128m
        - -XX:+UseG1GC
        - -Djava.security.egd=file:/dev/urandom
        - -Dspring.zipkin.enabled=false
        - -Dloader.path=/opt/lib
        - org.springframework.boot.loader.PropertiesLauncher
        - --port=8080
        command:
        - /usr/bin/java
        image: quay.io/powercloud/sock-shop-orders:v1.0-status-fix
        imagePullPolicy: IfNotPresent
        name: orders
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 300Mi
        securityContext:
          runAsNonRoot: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /tmp
          name: tmp-volume
      dnsPolicy: ClusterFirst
      nodeSelector:
        node-role.kubernetes.io/worker: ""
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir:
          medium: Memory
        name: tmp-volume
status:
  conditions:
  - lastTransitionTime: "2025-10-15T05:03:34Z"
    lastUpdateTime: "2025-10-28T07:33:56Z"
    message: ReplicaSet "orders-684c5d958c" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2025-10-28T07:44:43Z"
    lastUpdateTime: "2025-10-28T07:44:43Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  observedGeneration: 8
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1
