apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"prometheus.io/scrape":"true"},"labels":{"name":"payment"},"name":"payment","namespace":"sock-shop"},"spec":{"ports":[{"port":80,"targetPort":8080}],"selector":{"name":"payment"}}}
    prometheus.io/scrape: "true"
  creationTimestamp: "2025-10-14T11:10:58Z"
  labels:
    name: payment
  name: payment
  namespace: sock-shop
  resourceVersion: "53905"
  uid: 6b406dd1-fcb3-4b17-8f30-59cfd41d2e6b
spec:
  clusterIP: 10.96.100.12
  clusterIPs:
  - 10.96.100.12
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    name: payment
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
