apiVersion: v1
kind: ConfigMap
metadata:
  name: locustfile-crash
  namespace: sock-shop
data:
  locustfile.py: |
    from locust import HttpUser, task, between
    import random

    class SockShopUser(HttpUser):
        wait_time = between(0.5, 1.5)  # Aggressive timing
        
        @task(3)
        def browse_catalogue(self):
            self.client.get("/catalogue", name="Browse Catalogue")
        
        @task(2)
        def view_item(self):
            item_id = random.choice(["03fef6ac-1896-4ce8-bd69-b798f85c6e0b", 
                                      "510a0d7e-8e83-4193-b483-e27e09ddc34d",
                                      "808a2de1-1aaa-4c25-a9b9-6612e8f29a38"])
            self.client.get(f"/catalogue/{item_id}", name="View Item")
        
        @task(2)
        def add_to_cart(self):
            self.client.post("/cart", json={"id": "test-item"}, name="Add to Cart")
        
        @task(1)
        def login_attempt(self):
            self.client.get("/login", name="Login Page")
---
apiVersion: batch/v1
kind: Job
metadata:
  name: locust-crash-test
  namespace: sock-shop
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        app: locust-crash
    spec:
      restartPolicy: Never
      containers:
        - name: locust
          image: locustio/locust:2.32.1
          imagePullPolicy: IfNotPresent
          env:
            - name: LOCUST_HOST
              value: "http://front-end.sock-shop.svc.cluster.local"
            - name: USERS
              value: "3000"
            - name: SPAWN_RATE
              value: "300"
            - name: RUN_TIME
              value: "5m"
          volumeMounts:
            - name: locustfile
              mountPath: /mnt/locust
          workingDir: /mnt/locust
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "2000m"
              memory: "2Gi"
          command: ["sh", "-c"]
          args:
            - |
              echo "=========================================="
              echo "INCIDENT 1: CRASH TEST - STARTING"
              echo "Target: $LOCUST_HOST"
              echo "Users: $USERS | Spawn Rate: $SPAWN_RATE"
              echo "Duration: $RUN_TIME"
              echo "=========================================="
              locust -f locustfile.py \
                --host "$LOCUST_HOST" \
                --headless \
                -u "$USERS" \
                -r "$SPAWN_RATE" \
                --run-time "$RUN_TIME" \
                --html=/tmp/report.html
              echo "=========================================="
              echo "CRASH TEST COMPLETED"
              echo "=========================================="
      volumes:
        - name: locustfile
          configMap:
            name: locustfile-crash